spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL}

logging.level.org.springframework=${LOGGING_LEVEL_SPRINGFRAMEWORK}
logging.level.org.hibernate.SQL=${LOGGING_LEVEL_HIBERNATE_SQL}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=${LOGGING_LEVEL_HIBERNATE_BINDER}
spring.transaction.default-timeout=${SPRING_TRANSACTION_DEFAULT_TIMEOUT}
spring.transaction.rollback-on-commit-failure=${SPRING_TRANSACTION_ROLLBACK_ON_COMMIT_FAILURE}
spring.mvc.contentnegotiation.favor-path-extension=${SPRING_MVC_FAVOR_PATH_EXTENSION}
spring.mvc.contentnegotiation.favor-parameter=${SPRING_MVC_FAVOR_PARAMETER}
spring.mvc.contentnegotiation.media-types.json=${SPRING_MVC_JSON_MEDIA_TYPE}